# Usa una imagen oficial de PHP como base
FROM php:8.1-fpm

# Instala las dependencias necesarias (nginx, git, etc.)
RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip git && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd pdo pdo_mysql

# Instala Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Establece el directorio de trabajo
WORKDIR /var/www

# Copia los archivos de la aplicación Laravel a la imagen
COPY . /var/www

# Da permisos de escritura a los directorios de almacenamiento y caché
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

# Copia el archivo de configuración de Nginx (si existe)
# COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Expone el puerto de PHP-FPM
EXPOSE 9000

# Inicia PHP-FPM
CMD ["php-fpm"]
